# Generated by Django 4.2.6 on 2023-11-01 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "network_level",
                    models.CharField(
                        choices=[
                            ("FA", "Factory"),
                            ("DB", "Distributor"),
                            ("DC", "Dealer Center"),
                            ("LRC", "Large Retail Chain"),
                            ("IE", "Individual Entrepreneur"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("house_number", models.CharField(max_length=10)),
                ("debt", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("employee", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_networks",
                        to="manufacturer.network",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=25)),
                ("model", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
                ("network", models.ManyToManyField(to="manufacturer.network")),
            ],
        ),
    ]
