# Generated by Django 4.2.6 on 2023-10-31 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("manufacturer", "0001_initial")]

    operations = [migrations.RenameField(model_name="network", old_name="network", new_name="employee")]
